#!/usr/bin/env python
"""
Status check for outputs generated by 03_user_features.py.

For each category, we expect the following processed outputs to exist
on Google Drive (via the data registry):

  data/processed/<Category>/top_user_reviews_<Category>.parquet
  data/processed/<Category>/top_user_features_<Category>.parquet
  data/processed/<Category>/top_item_features_<Category>.parquet
  data/processed/<Category>/top_user_review_stats_<Category>.json
  data/processed/<Category>/top_users_rating_hist_<Category>.png
  data/processed/<Category>/top_users_helpful_hist_<Category>.png

For each expected file:
  - If it exists remotely, mark it OK.
  - Else, if it exists locally, upload it to Drive.
  - Else, record a failure for that category.

At the end, print a summary so we know which categories (if any) need
a manual re-run of 03_user_features.py.
"""

import argparse
import sys
from pathlib import Path
from typing import Dict, List

THIS_DIR = Path(__file__).resolve().parent
if str(THIS_DIR) not in sys.path:
    sys.path.insert(0, str(THIS_DIR))

from data_io import (  # noqa: E402
    resync_registry,
    ensure_local_path,
    upload_to_drive,
    remote_file_exists_by_rel_path,
)


def get_repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def read_all_categories_from_file(path: Path) -> List[str]:
    with open(path, "r", encoding="utf-8") as f:
        return [line.strip() for line in f if line.strip()]


def expected_files_for_category(repo_root: Path, category: str) -> List[Path]:
    """
    Build the list of expected processed outputs for a given category,
    matching 03_user_features.py.
    """
    cat_dir = repo_root / "data" / "processed" / category
    return [
        cat_dir / f"top_user_reviews_{category}.parquet",
        cat_dir / f"top_user_features_{category}.parquet",
        cat_dir / f"top_item_features_{category}.parquet",
        cat_dir / f"top_user_review_stats_{category}.json",
        cat_dir / f"top_users_rating_hist_{category}.png",
        cat_dir / f"top_users_helpful_hist_{category}.png",
    ]


def check_category(
    repo_root: Path, category: str
) -> Dict[str, List[str]]:
    """
    Check a single category's processed outputs.

    Returns a dict with keys:
      - "ok": list of files that are confirmed on Drive
      - "uploaded": list of files that were uploaded during this check
      - "missing": list of files missing both locally and remotely
    """
    results = {"ok": [], "uploaded": [], "missing": []}

    expected_paths = expected_files_for_category(repo_root, category)
    print(f"\n=== Status check: {category} ===")

    for p in expected_paths:
        rel = str(p.relative_to(repo_root))

        # 1) Check if file is known to exist remotely
        try:
            remote_exists = remote_file_exists_by_rel_path(rel)
        except Exception as e:
            print(f"  [warn] remote check failed for {rel}: {e}")
            remote_exists = False

        if remote_exists:
            print(f"  [ok] remote exists: {rel}")
            results["ok"].append(rel)
            continue

        # 2) Remote missing → check local filesystem
        if p.exists():
            print(f"  [upload] remote missing, local exists -> {rel}")
            try:
                upload_to_drive(p)
                print(f"  [upload] completed: {rel}")
                results["uploaded"].append(rel)
            except Exception as e:
                print(f"  [error] failed to upload {rel}: {e}")
                results["missing"].append(rel)
        else:
            # 3) No remote, no local → genuine missing artifact
            print(f"  [missing] neither remote nor local found: {rel}")
            results["missing"].append(rel)

    return results


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Check that 03_user_features outputs exist on Drive and upload any missing-but-local files."
    )
    parser.add_argument(
        "--categories",
        nargs="*",
        help="List of category names to check (default: all from data/raw/all_categories.txt).",
    )
    parser.add_argument(
        "--categories-file",
        type=str,
        default=None,
        help=(
            "Path to all_categories.txt (default: data/raw/all_categories.txt under repo)."
        ),
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    repo_root = get_repo_root()

    # Make sure registry is fresh so remote_file_exists_by_rel_path is meaningful
    print("[info] Resyncing data registry before status check...")
    resync_registry()

    # Determine categories
    if args.categories:
        categories = args.categories
        print(f"[info] Using categories from CLI: {categories}")
    else:
        if args.categories_file:
            cat_file = Path(args.categories_file)
            if not cat_file.is_absolute():
                cat_file = repo_root / cat_file
        else:
            cat_file = repo_root / "data" / "raw" / "all_categories.txt"

        categories = read_all_categories_from_file(cat_file)
        print(f"[info] No categories specified; using all from {cat_file}")
        print(f"[info] {len(categories)} categories: {categories}")

    categories_needing_rerun = []
    summary = {}

    for cat in categories:
        result = check_category(repo_root, cat)
        summary[cat] = result
        if result["missing"]:
            categories_needing_rerun.append(cat)

    print("\n==================== SUMMARY ====================")
    for cat, result in summary.items():
        print(f"\nCategory: {cat}")
        print(f"  OK on Drive   : {len(result['ok'])}")
        print(f"  Uploaded now  : {len(result['uploaded'])}")
        print(f"  Still missing : {len(result['missing'])}")
        if result["missing"]:
            print("    Missing files:")
            for rel in result["missing"]:
                print(f"      - {rel}")

    if categories_needing_rerun:
        print("\n[RESULT] Some categories are missing artifacts even after uploads.")
        print("         You likely need to re-run 03_user_features.py for:")
        for cat in categories_needing_rerun:
            print(f"  - {cat}")
    else:
        print("\n[RESULT] All expected 03_user_features outputs are present on Drive (or were uploaded just now).")


if __name__ == "__main__":
    main()
